// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfcXcY0LyQe1hwNdm9jgianhnz_paOwiQ',
    appId: '1:419030491018:web:a6ec9c76b77d09a178f273',
    messagingSenderId: '419030491018',
    projectId: 'instagramclone-e2de6',
    authDomain: 'instagramclone-e2de6.firebaseapp.com',
    storageBucket: 'instagramclone-e2de6.appspot.com',
    measurementId: 'G-0YJGRYSW14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGafUsOBOdwBFZSjb6WarB8oISTVazaRk',
    appId: '1:419030491018:android:a2f8f592d208772278f273',
    messagingSenderId: '419030491018',
    projectId: 'instagramclone-e2de6',
    storageBucket: 'instagramclone-e2de6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Hfh-Hosg8hB3bgTULvlYgh46Tscd-cY',
    appId: '1:419030491018:ios:f8a3191c026d5b8c78f273',
    messagingSenderId: '419030491018',
    projectId: 'instagramclone-e2de6',
    storageBucket: 'instagramclone-e2de6.appspot.com',
    iosBundleId: 'com.example.flutterInstaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Hfh-Hosg8hB3bgTULvlYgh46Tscd-cY',
    appId: '1:419030491018:ios:4f3d9c7780d8192a78f273',
    messagingSenderId: '419030491018',
    projectId: 'instagramclone-e2de6',
    storageBucket: 'instagramclone-e2de6.appspot.com',
    iosBundleId: 'com.example.flutterInstaClone.RunnerTests',
  );
}
